

/* PAGE COLLECTION */

export const FETCH_PAGES = "FETCH_PAGES"
export const RECEIVE_PAGES = "RECEIVE_PAGES"
export const PAGE_ACTION = "PAGE_ACTION"


/////////
/////////
/////////


/* MEDIA BROWSER */

export const MEDIA_BROWSER_SHOW = "MEDIA_BROWSER_SHOW"
export const MEDIA_BROWSER_HIDE = "MEDIA_BROWSER_HIDE"
export const MEDIA_BROWSER_NAVIGATE = "MEDIA_BROWSER_NAVIGATE"
export const MEDIA_BROWSER_RECEIVE = "MEDIA_BROWSER_RECEIVE"
export const MEDIA_BROWSER_FAIL = "MEDIA_BROWSER_FAIL"
export const MEDIA_BROWSER_SELECT = "MEDIA_BROWSER_SELECT"
export const MEDIA_BROWSER_CONFIRM = 'MEDIA_BROWSER_CONFIRM'
export const MEDIA_BROWSER_ACKNOWLEDGE = 'MEDIA_BROWSER_ACKNOWLEDGE'


/////////
/////////
/////////


/* PAGE BROWSER */

export const PAGE_BROWSER_SHOW = "PAGE_BROWSER_SHOW"
export const PAGE_BROWSER_HIDE = "PAGE_BROWSER_HIDE"
export const PAGE_BROWSER_NAVIGATE = "PAGE_BROWSER_NAVIGATE"
export const PAGE_BROWSER_RECEIVE = "PAGE_BROWSER_RECEIVE"
export const PAGE_BROWSER_FAIL = "PAGE_BROWSER_FAIL"
export const PAGE_BROWSER_SELECT = "PAGE_BROWSER_SELECT"
export const PAGE_BROWSER_CONFIRM = 'PAGE_BROWSER_CONFIRM'
export const PAGE_BROWSER_ACKNOWLEDGE = 'PAGE_BROWSER_ACKNOWLEDGE'


/////////
/////////
/////////

/* STATIC REPO */

export const STATIC_REPO_CHECK_SEND = "STATIC_REPO_CHECK_SEND"
export const STATIC_REPO_CHECK_RECEIVE = "STATIC_REPO_CHECK_RECEIVE"
export const STATIC_REPO_IMPORT_SEND = "STATIC_REPO_IMPORT_SEND"
export const STATIC_REPO_IMPORT_RECEIVE = "STATIC_REPO_IMPORT_RECEIVE"


/////////
/////////
/////////

/* AUTH */

export const AUTH_CHECK_SEND = "AUTH_CHECK_SEND"
export const AUTH_CHECK_RECEIVE = "AUTH_CHECK_RECEIVE"
export const AUTH_LOGIN_SEND = "AUTH_LOGIN_SEND"
export const AUTH_LOGIN_RECEIVE = "AUTH_LOGIN_RECEIVE"