

/* PAGE COLLECTION */

export const FETCH_PAGES = "FETCH_PAGES"
export const RECEIVE_PAGES = "RECEIVE_PAGES"
export const PAGE_REMOVED = "PAGE_REMOVED"
export const PAGE_ACTION = "PAGE_ACTION"


/////////
/////////
/////////

/* STATIC REPO */

export const STATIC_REPO_CHECK_SEND = "STATIC_REPO_CHECK_SEND"
export const STATIC_REPO_CHECK_RECEIVE = "STATIC_REPO_CHECK_RECEIVE"
export const STATIC_REPO_IMPORT_SEND = "STATIC_REPO_IMPORT_SEND"
export const STATIC_REPO_IMPORT_RECEIVE = "STATIC_REPO_IMPORT_RECEIVE"


/////////
/////////
/////////

/* AUTH */

export const AUTH_CHECK_SEND = "AUTH_CHECK_SEND"
export const AUTH_CHECK_RECEIVE = "AUTH_CHECK_RECEIVE"
export const AUTH_LOGIN_SEND = "AUTH_LOGIN_SEND"
export const AUTH_LOGIN_RECEIVE = "AUTH_LOGIN_RECEIVE"
export const AUTH_EXPIRE = "AUTH_EXPIRE"