

const SOCIAL_LINKS_ACTION_TYPES = {
    ADD_LINK: "ADD_LINK",
    MODIFY_LINK: "MODIFY_LINK",
    SWAP_LINKS: "SWAP_LINKS",
    REMOVE_LINK: "REMOVE_LINK"
}


export default SOCIAL_LINKS_ACTION_TYPES