

const BLOG_PAGE_ACTION_TYPES = {
    SET_TITLE: "SET_TITLE",
    SET_IMG_SRC: "SET_IMG_SRC",
    HAS_MODIFIED: "HAS_MODIFIED",
    PUBLISH: "PUBLISH",
    UNPUBLISH: "UNPUBLISH"
}

export default BLOG_PAGE_ACTION_TYPES