
const IMAGE_ACTION_TYPES = {
    UPDATE_SRC: "UPDATE_SRC",
    UPADTE_ALT: "UPDATE_ALT",
    SET_PAGE_LINK: "SET_PAGE_LINK",
    SET_EXTERNAL_LINK: "SET_EXTERNAL_LINK"
}

export default IMAGE_ACTION_TYPES