
//
export const TEXT_BLOCK_ALIGNMENT_STATES = {
    LEFT: "LEFT",
    CENTER: "CENTER",
    RIGHT: "RIGHT",
    JUSTIFIED: "JUSTIFIED"
}
//

const TEXT_BLOCK_ACTION_TYPES = {
    UPDATE_EDITOR_STATE: "UPDATE_EDITOR_STATE",
    SET_ALIGNMENT: "SET_ALIGNMENT"
}

export default TEXT_BLOCK_ACTION_TYPES